### ISSUE TITLE
wg0 already exists and no internet after install

### ISSUE THREAD

**Issue by drwwww** [hsand/pia-wg#1]
I'm trying to set this up on Raspbian "buster." I followed the instructions, but when I run the last command:

`sudo wg-quick up wg0`

I get the following message:

`wg-quick: 'wg0' already exists`

And also now the device no longer has internet access while still being accessible over LAN.

**Comment by drwwww** [comment]
> And also now the device no longer has internet access while still being accessible over LAN.

This was fixed by resetting my default gateway:
`sudo ip route add default via 192.168.1.xxx`

**Comment by hsand** [comment]
This sounds like you're having issues with an existing Wireguard interface. When you copy the configuration file to /etc/wireguard/ try giving it a different name. i.e. wg1.

If this doesn't solve the issue, I suspect this is related to the wg-quick application, and not the pia-wg script. The pia-wg script just creates configuration files that can be used by Wireguard. wg-quick is the application that sets up the interface.
