### ISSUE TITLE
ERROR: Conflicting Dependencies

### ISSUE THREAD

**Issue by flamingfury472** [hsand/pia-wg#6]
Please excuse my lack of python knowledge. Your how-to is very user friendly, however I have a dependency error that I do not know how to resolve. Here is the text from the command line:

**ERROR: Cannot install -r requirements.txt (line 5) and urllib3==1.26.6 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested urllib3==1.26.6
    requests 2.24.0 depends on urllib3!=1.25.0, !=1.25.1, <1.26 and >=1.21.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies**

Thank you for your assistance.

**Comment by JSaterdalen** [comment]
@flamingfury472 I submitted a pull request to fix this issue. In the meantime, you can edit your requirements.txt file by changing the 'requests' version to 2.26.0. That will allow you to install requirements without conflicts.
